In [1]:
import pandas as pd

# File paths
file_paths = {
    "log2cna": "../Datafiles Final/Datafiles Cleaned/log2cna.pkl",
    "methylation": "../Datafiles Final/Datafiles Cleaned/methylation.pkl",
    "mrnaseqv2": "../Datafiles Final/Datafiles Cleaned/mrnaseqv2.pkl"
}

# Function to load and display data
def load_and_display_pkl(file_path, dataset_name):
    df = pd.read_pickle(file_path)
    print(f"\nDisplaying first 5 rows of {dataset_name}:")
    display(df.head())  # Jupyter-friendly display

In [2]:
file_paths["methylation"]

'../Datafiles Final/Datafiles Cleaned/methylation.pkl'

In [3]:
load_and_display_pkl(file_paths["methylation"],"methylation")

Displaying first 5 rows of methylation:

,0,1,2,3,4,5,6,7,8,9,...,22591,22592,22593,22594,22595,22596,22597,22598,22599,22600
ENTITY_STABLE_ID,cg00000292,cg00003994,cg00005847,cg00007981,cg00008493,cg00008713,cg00009407,cg00011459,cg00012199,cg00012386,...,cg27651218,cg27652350,cg27653134,cg27654142,cg27655905,cg27657283,cg27661264,cg27662379,cg27662877,cg27665659
NAME,ATP2A1,MEOX2,HOXD3,PANX1,KIAA1409;COX8C,IMPA2,TTC8,PMM2;TMEM186,ANG;RNASE4,SNAP47;JMJD4,...,KIAA1409;COX8C,ALDH1A3,A2ML1,ZFP2,C11orf24,LEPRE1;C1orf50,GNAS,RPN1,CYB5A,AP1S1
TCGA-04-1331-01,0.931225,0.04703,0.810362,0.011909,0.942704,0.054855,0.048007,0.865935,0.03578,0.038247,...,0.940881,0.97275,0.442261,0.036939,0.052637,0.027384,0.087231,0.045186,0.03732,0.043665
TCGA-04-1332-01,0.527324,0.055236,0.372304,0.008184,0.932735,0.054339,0.050471,0.876822,0.026227,0.024022,...,0.920633,0.828132,0.856183,0.037255,0.051982,0.014439,0.332597,0.046139,0.04535,0.060061
TCGA-04-1335-01,0.915472,0.084291,0.641705,0.029346,0.943137,0.026842,0.077507,0.712961,0.047387,0.027316,...,0.941942,0.951807,0.584416,0.034934,0.055217,0.076347,0.395181,0.04262,0.050956,0.040036

In [4]:
load_and_display_pkl( file_paths["mrnaseqv2"],"mrnaseqv2")

Displaying first 5 rows of mrnaseqv2:

,0,1,2,3,4,5,6,7,8,9,...,19066,19067,19068,19069,19070,19071,19072,19073,19074,19075
Hugo_Symbol,UBE2Q2P3,UBE2Q2P2,HMGB1P1,TIMM23,LOC155060,RNU12-2P,EZHIP,EFCAB8,SRP14P1,TRIM75P,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
Entrez_Gene_Id,100133144,100134869,10357,10431,155060,26823,340602,388795,390284,391714,...,55055,11130,7789,158586,79364,440590,79699,7791,23140,26009
TCGA-04-1348-01,22.028266,25.716221,321.241331,1952.678661,222.150613,0.676632,-0.059851,3.038671,4.594825,-0.329284,...,1018.226589,1181.934902,25.685296,189.275552,784.054335,6.82465,483.94279,9692.870954,429.818654,475.233973
TCGA-04-1357-01,17.671802,20.473921,128.865135,901.425735,244.41232,0.09028,-0.479632,4.932117,5.20536,-0.329284,...,213.949506,323.811661,79.007175,469.565537,1177.56175,4.775693,518.654716,3284.754545,684.474498,414.753874
TCGA-04-1362-01,21.97672,29.90998,424.021806,1366.864827,377.449014,0.451162,4.514755,3.434062,4.371905,0.780617,...,462.214865,900.545359,66.976049,634.928214,1493.09879,66.80088,791.336454,3747.937644,766.2498,802.717598

In [5]:
load_and_display_pkl( file_paths["log2cna"],"log2cna")

Displaying first 5 rows of log2cna:

,0,1,2,3,4,5,6,7,8,9,...,25118,25119,25120,25121,25122,25123,25124,25125,25126,25127
Hugo_Symbol,ACAP3,ACTRT2,AGRN,ANKRD65,ATAD3A,ATAD3B,ATAD3C,AURKAIP1,B3GALT6,C1orf159,...,hsa-mir-1321,hsa-mir-361,hsa-mir-548m,hsa-mir-652,hsa-mir-220a,hsa-mir-513c,hsa-mir-513b,hsa-mir-513a-1,hsa-mir-513a-2,hsa-mir-224
Entrez_Gene_Id,116983.0,140625.0,375790.0,441869.0,55210.0,83858.0,219293.0,54998.0,126792.0,54991.0,...,100302171.0,494323.0,100302151.0,724022.0,407005.0,100302114.0,100302253.0,NaN,574510.0,NaN
TCGA-04-1331-01,-0.704,-0.704,-0.704,-0.704,-0.704,-0.704,-0.704,-0.704,-0.704,-0.704,...,0.036,0.036,-0.372,-0.348,-0.348,-0.368,-0.368,-0.368,-0.368,-0.368
TCGA-04-1332-01,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,...,-0.237,-0.237,-0.237,-0.237,-0.237,-0.256,-0.256,-0.256,-0.256,-0.256
TCGA-04-1335-01,-0.807,-0.807,-0.807,-0.807,-0.807,-0.807,-0.807,-0.807,-0.807,-0.807,...,0.063,0.063,0.063,0.049,0.071,0.071,0.071,0.071,0.071,0.673